language: node_js
node_js:
- stable
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_4a2166934298_key -iv $encrypted_4a2166934298_iv
  -in .travis/id_rsa_github_io.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
install:
- npm install -g hexo-cli
- hexo init hexo-empty
- pushd hexo-empty
- npm install
- popd
- mv hexo-empty/node_modules ./
- mv hexo-empty/package.json ./
before_script:
- git config --global user.name 'lixingcong'
- git config --global user.email 'lixingcong@live.com'
- git submodule update --init --recursive
script:
- hexo g && bash deploy.sh
