language: node_js
node_js:
- stable
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_4a2166934298_key -iv $encrypted_4a2166934298_iv
  -in .travis/id_rsa_github_io.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
install:
- npm install -g hexo-cli
- hexo init temp_lxc
- cd temp_lxc
- npm install
before_script:
- mv ../source ./
- mv ../themes ./
- mv ../_config.yml ./
- mv ../deploy.sh ./
- git config --global user.name 'lixingcong'
- git config --global user.email 'lixingcong@live.com'
script:
- hexo g && bash deploy.sh
